inherits: [iga.yml]
population:
  type: nsga_ii
  size: 100
  selection: crowded_tournament
  combinepop: front_elitist
  subset:
    type: evenfront
    size: 9
application:
  name: docdesign
  images: [p1.png, p2.png, p3.png]
  vars:
    x: 
        max: 0.7
        min: 0.
        scale: 0.01
    y: 
        max: 0.7
        min: 0.
        scale: 0.01
    s: 
        max: 1.5
        min: 0.2
        scale: 0.01
    r: 
        max: 90.
        min: 0.
        scale: 1.
